version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.15
    - 8.0.16
    - 9.0.0
    - 9.0.2
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.21
    - 0.20.22
    - 0.20.23
